services:
  - type: web
    name: Trade-Signal-bot-101
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -c gunicorn.conf.py wsgi:app"
    envVars:
      - key: PORT
        value: "5000"